theme: minima
title: Marcelino Anguiano
author: I am the author MA
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website (under construction)
 
# social links
linkedin_username: marcelino-anguiano-74083685
twitter_username: NONE # DO NOT include the @ character, or else the build will fail!
github_username:  NONE # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
